//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerSimulation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultRawFile {
            get {
                return ((string)(this["DefaultRawFile"]));
            }
            set {
                this["DefaultRawFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogPath {
            get {
                return ((string)(this["LogPath"]));
            }
            set {
                this["LogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rsf, rf")]
        public string RoyalStraightFlushIdentifiers {
            get {
                return ((string)(this["RoyalStraightFlushIdentifiers"]));
            }
            set {
                this["RoyalStraightFlushIdentifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sf")]
        public string StraightFlushIdentifiers {
            get {
                return ((string)(this["StraightFlushIdentifiers"]));
            }
            set {
                this["StraightFlushIdentifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("st")]
        public string StraightIdentifiers {
            get {
                return ((string)(this["StraightIdentifiers"]));
            }
            set {
                this["StraightIdentifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fl")]
        public string FlushIdentifiers {
            get {
                return ((string)(this["FlushIdentifiers"]));
            }
            set {
                this["FlushIdentifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fk")]
        public string FourOfAKindIdentifiers {
            get {
                return ((string)(this["FourOfAKindIdentifiers"]));
            }
            set {
                this["FourOfAKindIdentifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fh")]
        public string FullHouseIdentifiers {
            get {
                return ((string)(this["FullHouseIdentifiers"]));
            }
            set {
                this["FullHouseIdentifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tk")]
        public string ThreeOfAKindIdentifiers {
            get {
                return ((string)(this["ThreeOfAKindIdentifiers"]));
            }
            set {
                this["ThreeOfAKindIdentifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tp")]
        public string TwoPairIdentifiers {
            get {
                return ((string)(this["TwoPairIdentifiers"]));
            }
            set {
                this["TwoPairIdentifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("op")]
        public string OnePairIdentifiers {
            get {
                return ((string)(this["OnePairIdentifiers"]));
            }
            set {
                this["OnePairIdentifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hc")]
        public string HighCardIdentifiers {
            get {
                return ((string)(this["HighCardIdentifiers"]));
            }
            set {
                this["HighCardIdentifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9, rsf, rf")]
        public string RoyalStraightFlushFileTokens {
            get {
                return ((string)(this["RoyalStraightFlushFileTokens"]));
            }
            set {
                this["RoyalStraightFlushFileTokens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8, sf")]
        public string StraightFlushFileTokens {
            get {
                return ((string)(this["StraightFlushFileTokens"]));
            }
            set {
                this["StraightFlushFileTokens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4, st")]
        public string StraightFileTokens {
            get {
                return ((string)(this["StraightFileTokens"]));
            }
            set {
                this["StraightFileTokens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5, fl")]
        public string FlushFileTokens {
            get {
                return ((string)(this["FlushFileTokens"]));
            }
            set {
                this["FlushFileTokens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7, fk")]
        public string FourOfAKindFileTokens {
            get {
                return ((string)(this["FourOfAKindFileTokens"]));
            }
            set {
                this["FourOfAKindFileTokens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6, fh")]
        public string FullHouseFileTokens {
            get {
                return ((string)(this["FullHouseFileTokens"]));
            }
            set {
                this["FullHouseFileTokens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, tk")]
        public string ThreeOfAKindFileTokens {
            get {
                return ((string)(this["ThreeOfAKindFileTokens"]));
            }
            set {
                this["ThreeOfAKindFileTokens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2, tp")]
        public string TwoPairFileTokens {
            get {
                return ((string)(this["TwoPairFileTokens"]));
            }
            set {
                this["TwoPairFileTokens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1, op")]
        public string OnePairFileTokens {
            get {
                return ((string)(this["OnePairFileTokens"]));
            }
            set {
                this["OnePairFileTokens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, hc")]
        public string HighCardFileTokens {
            get {
                return ((string)(this["HighCardFileTokens"]));
            }
            set {
                this["HighCardFileTokens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("High Card")]
        public string HighCardString {
            get {
                return ((string)(this["HighCardString"]));
            }
            set {
                this["HighCardString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One Pair")]
        public string OnePairString {
            get {
                return ((string)(this["OnePairString"]));
            }
            set {
                this["OnePairString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Two Pair")]
        public string TwoPairString {
            get {
                return ((string)(this["TwoPairString"]));
            }
            set {
                this["TwoPairString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Three of a Kind")]
        public string ThreeOfAKindString {
            get {
                return ((string)(this["ThreeOfAKindString"]));
            }
            set {
                this["ThreeOfAKindString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Full House")]
        public string FullHouseString {
            get {
                return ((string)(this["FullHouseString"]));
            }
            set {
                this["FullHouseString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Four of a Kind")]
        public string FourOfAKindString {
            get {
                return ((string)(this["FourOfAKindString"]));
            }
            set {
                this["FourOfAKindString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flush")]
        public string FlushString {
            get {
                return ((string)(this["FlushString"]));
            }
            set {
                this["FlushString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Straight")]
        public string StraightString {
            get {
                return ((string)(this["StraightString"]));
            }
            set {
                this["StraightString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Straight Flush")]
        public string StraightFlushString {
            get {
                return ((string)(this["StraightFlushString"]));
            }
            set {
                this["StraightFlushString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Royal Flush")]
        public string RoyalFlushString {
            get {
                return ((string)(this["RoyalFlushString"]));
            }
            set {
                this["RoyalFlushString"] = value;
            }
        }
    }
}
